server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgre
    password: Indrinf3110
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ganifaturrozak11@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false